name: Metrics

on:
  schedule:
    - cron: "12 18 * * *"
  workflow_dispatch:
  push:
    branches:
      - master
      - main

permissions:
  contents: write

concurrency:
  group: metrics-${{ github.ref }}
  cancel-in-progress: true

jobs:
  github-metrics:
    runs-on: ubuntu-latest
    steps:
      - name: Isometric commit calendar
        uses: lowlighter/metrics@latest
        with:
          filename: metrics/isocalendar.svg
          token: ${{ secrets.METRICS_TOKEN }}
          user: JklvJohny
          base: ""
          plugin_isocalendar: yes
          plugin_isocalendar_duration: full-year
          config_timezone: Asia/Bangkok

      - name: Languages activity
        uses: lowlighter/metrics@latest
        with:
          filename: metrics/languages.svg
          token: ${{ secrets.METRICS_TOKEN }}
          user: JklvJohny
          base: ""
          plugin_languages: yes
          plugin_languages_sections: most-used, recently-used
          plugin_languages_details: bytes-size, percentage
          plugin_languages_limit: 8
          plugin_languages_threshold: 0%
          plugin_languages_other: yes

      - name: Coding habits and activity
        uses: lowlighter/metrics@latest
        with:
          filename: metrics/habits.svg
          token: ${{ secrets.METRICS_TOKEN }}
          user: JklvJohny
          base: ""
          plugin_habits: yes
          plugin_habits_from: 300
          plugin_habits_days: 30
          plugin_habits_facts: yes
          plugin_habits_charts: yes
          plugin_habits_charts_type: graph
          plugin_habits_trim: yes
          plugin_habits_languages_limit: 8
          config_timezone: Asia/Bangkok

      - name: Follow-up of issues and pull requests
        uses: lowlighter/metrics@latest
        with:
          filename: metrics/followup.svg
          token: ${{ secrets.METRICS_TOKEN }}
          user: JklvJohny
          base: ""
          plugin_followup: yes
          plugin_followup_sections: repositories, user
          plugin_followup_indepth: yes
          plugin_followup_archived: no

      - name: Google PageSpeed
        uses: lowlighter/metrics@latest
        with:
          filename: metrics/pagespeed.svg
          token: ${{ secrets.METRICS_TOKEN }}
          user: JklvJohny
          base: ""
          plugin_pagespeed: yes
          plugin_pagespeed_token: ${{ secrets.PAGESPEED_TOKEN }}
          plugin_pagespeed_url: https://github.com/JklvJohny
          plugin_pagespeed_detailed: yes
          plugin_pagespeed_pwa: yes
